services:
  - type: web
    name: hwlx-web-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
