name: Keep Alive Self

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  self:
    runs-on: ubuntu-latest
    steps:
      - name: Self check
        run: |
          echo "Self keep alive check"
          echo "Timestamp: $(date)"
          echo "Job completed successfully"
