name: Keep Alive Reliable

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check website status
        run: |
          echo "=== 保活检查开始 ==="
          echo "时间: $(date)"
          echo "目标: https://hai-wai-liu-xue.onrender.com"
          
          # 方法1: 使用wget
          echo "方法1: 使用wget..."
          wget --quiet --spider https://hai-wai-liu-xue.onrender.com && echo "✅ wget成功" || echo "❌ wget失败"
          
          # 方法2: 使用curl
          echo "方法2: 使用curl..."
          curl -s -o /dev/null -w "状态码: %{http_code}\n" https://hai-wai-liu-xue.onrender.com
          
          # 方法3: 使用ping (如果可用)
          echo "方法3: 检查网络连接..."
          ping -c 1 8.8.8.8 > /dev/null && echo "✅ 网络连接正常" || echo "⚠️ 网络连接异常"
          
          echo "=== 保活检查完成 ==="
