name: Keep Alive Wget

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check website with wget
        run: |
          echo "使用wget检查网站..."
          wget --spider --timeout=30 https://hai-wai-liu-xue.onrender.com
          echo "检查完成"
